/* =========================================
   BASE DE DATOS DE ELEMENTOS QUÍMICOS
   Tabla Periódica Interactiva - meskeIA
   118 elementos con propiedades completas
   ========================================= */

const elementosQuimicos = [
    // Período 1
    {
        numero: 1,
        simbolo: "H",
        nombre: "Hidrógeno",
        masa: 1.008,
        grupo: 1,
        periodo: 1,
        familia: "no-metales",
        estado: "gas",
        electronegatividad: 2.20,
        radioAtomico: 53,
        configuracionElectronica: "1s¹",
        usos: ["Combustible en cohetes", "Soldadura", "Refinado de petróleo", "Producción de amoníaco"],
        datoCurioso: "Es el elemento más abundante del universo, constituyendo aproximadamente el 75% de la materia visible.",
        descubrimiento: "1766 por Henry Cavendish",
        posicion: { fila: 1, columna: 1 }
    },
    {
        numero: 2,
        simbolo: "He",
        nombre: "Helio",
        masa: 4.003,
        grupo: 18,
        periodo: 1,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: null,
        radioAtomico: 31,
        configuracionElectronica: "1s²",
        usos: ["Globos y dirigibles", "Respiración profunda", "Criogenia", "Detectores de fugas"],
        datoCurioso: "Es el segundo elemento más abundante del universo, pero raro en la Tierra porque escapa al espacio.",
        descubrimiento: "1868 por Pierre Janssen y Norman Lockyer",
        posicion: { fila: 1, columna: 18 }
    },

    // Período 2
    {
        numero: 3,
        simbolo: "Li",
        nombre: "Litio",
        masa: 6.941,
        grupo: 1,
        periodo: 2,
        familia: "metales-alcalinos",
        estado: "solido",
        electronegatividad: 0.98,
        radioAtomico: 167,
        configuracionElectronica: "[He] 2s¹",
        usos: ["Baterías de ion-litio", "Medicamentos psiquiátricos", "Aleaciones", "Vidrio y cerámica"],
        datoCurioso: "Es el metal más ligero y puede flotar en el agua, aunque reacciona violentamente con ella.",
        descubrimiento: "1817 por Johan August Arfvedson",
        posicion: { fila: 2, columna: 1 }
    },
    {
        numero: 4,
        simbolo: "Be",
        nombre: "Berilio",
        masa: 9.012,
        grupo: 2,
        periodo: 2,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 1.57,
        radioAtomico: 112,
        configuracionElectronica: "[He] 2s²",
        usos: ["Aleaciones aeroespaciales", "Rayos X (ventanas)", "Reactores nucleares", "Herramientas antichispa"],
        datoCurioso: "Es extremadamente tóxico y carcinógeno, pero indispensable en la industria aeroespacial.",
        descubrimiento: "1797 por Louis-Nicolas Vauquelin",
        posicion: { fila: 2, columna: 2 }
    },
    {
        numero: 5,
        simbolo: "B",
        nombre: "Boro",
        masa: 10.811,
        grupo: 13,
        periodo: 2,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.04,
        radioAtomico: 87,
        configuracionElectronica: "[He] 2s² 2p¹",
        usos: ["Vidrio borosilicato", "Detergentes", "Insecticidas", "Semiconductores"],
        datoCurioso: "Forma enlaces químicos únicos que desafían las reglas tradicionales de valencia.",
        descubrimiento: "1808 por Sir Humphry Davy y Joseph Louis Gay-Lussac",
        posicion: { fila: 2, columna: 13 }
    },
    {
        numero: 6,
        simbolo: "C",
        nombre: "Carbono",
        masa: 12.011,
        grupo: 14,
        periodo: 2,
        familia: "no-metales",
        estado: "solido",
        electronegatividad: 2.55,
        radioAtomico: 67,
        configuracionElectronica: "[He] 2s² 2p²",
        usos: ["Base de toda vida orgánica", "Acero", "Diamantes", "Grafito", "Combustibles fósiles"],
        datoCurioso: "Puede formar más compuestos que cualquier otro elemento, base de toda la química orgánica.",
        descubrimiento: "Prehistórico (carbón y hollín)",
        posicion: { fila: 2, columna: 14 }
    },
    {
        numero: 7,
        simbolo: "N",
        nombre: "Nitrógeno",
        masa: 14.007,
        grupo: 15,
        periodo: 2,
        familia: "no-metales",
        estado: "gas",
        electronegatividad: 3.04,
        radioAtomico: 56,
        configuracionElectronica: "[He] 2s² 2p³",
        usos: ["Fertilizantes", "Explosivos", "Atmósfera inerte", "Criogenia", "Proteínas"],
        datoCurioso: "Constituye el 78% de la atmósfera terrestre, pero es químicamente inerte en su forma molecular.",
        descubrimiento: "1772 por Daniel Rutherford",
        posicion: { fila: 2, columna: 15 }
    },
    {
        numero: 8,
        simbolo: "O",
        nombre: "Oxígeno",
        masa: 15.999,
        grupo: 16,
        periodo: 2,
        familia: "no-metales",
        estado: "gas",
        electronegatividad: 3.44,
        radioAtomico: 48,
        configuracionElectronica: "[He] 2s² 2p⁴",
        usos: ["Respiración", "Combustión", "Medicina", "Soldadura", "Tratamiento de aguas"],
        datoCurioso: "Es el elemento más abundante en la corteza terrestre y es paramagnético en estado líquido.",
        descubrimiento: "1774 por Joseph Priestley y Carl Wilhelm Scheele",
        posicion: { fila: 2, columna: 16 }
    },
    {
        numero: 9,
        simbolo: "F",
        nombre: "Flúor",
        masa: 18.998,
        grupo: 17,
        periodo: 2,
        familia: "halogenos",
        estado: "gas",
        electronegatividad: 3.98,
        radioAtomico: 42,
        configuracionElectronica: "[He] 2s² 2p⁵",
        usos: ["Pasta dental", "Teflón", "Refrigerantes", "Enriquecimiento de uranio"],
        datoCurioso: "Es el elemento más electronegativo y reactivo, puede reaccionar con casi cualquier elemento.",
        descubrimiento: "1886 por Henri Moissan",
        posicion: { fila: 2, columna: 17 }
    },
    {
        numero: 10,
        simbolo: "Ne",
        nombre: "Neón",
        masa: 20.180,
        grupo: 18,
        periodo: 2,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: null,
        radioAtomico: 38,
        configuracionElectronica: "[He] 2s² 2p⁶",
        usos: ["Letreros luminosos", "Láseres", "Criogenia", "Indicadores de alto voltaje"],
        datoCurioso: "Produce una luz naranja-rojiza característica cuando se electrifica en tubos de descarga.",
        descubrimiento: "1898 por William Ramsay y Morris Travers",
        posicion: { fila: 2, columna: 18 }
    },

    // Período 3
    {
        numero: 11,
        simbolo: "Na",
        nombre: "Sodio",
        masa: 22.990,
        grupo: 1,
        periodo: 3,
        familia: "metales-alcalinos",
        estado: "solido",
        electronegatividad: 0.93,
        radioAtomico: 190,
        configuracionElectronica: "[Ne] 3s¹",
        usos: ["Sal de mesa", "Lámparas de vapor", "Aleaciones", "Refrigerante nuclear"],
        datoCurioso: "Es tan reactivo que se almacena en aceite para evitar su reacción con el aire y la humedad.",
        descubrimiento: "1807 por Sir Humphry Davy",
        posicion: { fila: 3, columna: 1 }
    },
    {
        numero: 12,
        simbolo: "Mg",
        nombre: "Magnesio",
        masa: 24.305,
        grupo: 2,
        periodo: 3,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 1.31,
        radioAtomico: 145,
        configuracionElectronica: "[Ne] 3s²",
        usos: ["Aleaciones ligeras", "Fuegos artificiales", "Medicina (antiácidos)", "Automoción"],
        datoCurioso: "Arde con una llama blanca brillante y es esencial para la clorofila en las plantas.",
        descubrimiento: "1755 por Joseph Black",
        posicion: { fila: 3, columna: 2 }
    },
    {
        numero: 13,
        simbolo: "Al",
        nombre: "Aluminio",
        masa: 26.982,
        grupo: 13,
        periodo: 3,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.61,
        radioAtomico: 118,
        configuracionElectronica: "[Ne] 3s² 3p¹",
        usos: ["Envases", "Construcción", "Transporte", "Cables eléctricos", "Aleaciones"],
        datoCurioso: "Una vez fue más valioso que el oro debido a la dificultad de su extracción.",
        descubrimiento: "1825 por Hans Christian Ørsted",
        posicion: { fila: 3, columna: 13 }
    },
    {
        numero: 14,
        simbolo: "Si",
        nombre: "Silicio",
        masa: 28.086,
        grupo: 14,
        periodo: 3,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 1.90,
        radioAtomico: 111,
        configuracionElectronica: "[Ne] 3s² 3p²",
        usos: ["Semiconductores", "Vidrio", "Cemento", "Cerámicas", "Circuitos integrados"],
        datoCurioso: "Es el segundo elemento más abundante en la corteza terrestre y base de la revolución digital.",
        descubrimiento: "1824 por Jöns Jacob Berzelius",
        posicion: { fila: 3, columna: 14 }
    },
    {
        numero: 15,
        simbolo: "P",
        nombre: "Fósforo",
        masa: 30.974,
        grupo: 15,
        periodo: 3,
        familia: "no-metales",
        estado: "solido",
        electronegatividad: 2.19,
        radioAtomico: 98,
        configuracionElectronica: "[Ne] 3s² 3p³",
        usos: ["Fertilizantes", "Cerillas", "Detergentes", "DNA/RNA", "Huesos y dientes"],
        datoCurioso: "Existe en varias formas alotrópicas, incluyendo el fósforo blanco que brilla en la oscuridad.",
        descubrimiento: "1669 por Hennig Brand",
        posicion: { fila: 3, columna: 15 }
    },
    {
        numero: 16,
        simbolo: "S",
        nombre: "Azufre",
        masa: 32.065,
        grupo: 16,
        periodo: 3,
        familia: "no-metales",
        estado: "solido",
        electronegatividad: 2.58,
        radioAtomico: 88,
        configuracionElectronica: "[Ne] 3s² 3p⁴",
        usos: ["Ácido sulfúrico", "Vulcanización del caucho", "Fertilizantes", "Medicina", "Pólvora"],
        datoCurioso: "Conocido desde la antigüedad, se asociaba con el fuego del infierno por su olor característico.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 3, columna: 16 }
    },
    {
        numero: 17,
        simbolo: "Cl",
        nombre: "Cloro",
        masa: 35.453,
        grupo: 17,
        periodo: 3,
        familia: "halogenos",
        estado: "gas",
        electronegatividad: 3.16,
        radioAtomico: 79,
        configuracionElectronica: "[Ne] 3s² 3p⁵",
        usos: ["Desinfectante", "Lejía", "PVC", "Tratamiento de agua", "Productos químicos"],
        datoCurioso: "Fue usado como arma química en la Primera Guerra Mundial debido a su toxicidad.",
        descubrimiento: "1774 por Carl Wilhelm Scheele",
        posicion: { fila: 3, columna: 17 }
    },
    {
        numero: 18,
        simbolo: "Ar",
        nombre: "Argón",
        masa: 39.948,
        grupo: 18,
        periodo: 3,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: null,
        radioAtomico: 71,
        configuracionElectronica: "[Ne] 3s² 3p⁶",
        usos: ["Soldadura", "Lámparas incandescentes", "Ventanas aislantes", "Preservación"],
        datoCurioso: "Constituye casi el 1% de la atmósfera terrestre, siendo el tercer gas más abundante.",
        descubrimiento: "1894 por Lord Rayleigh y William Ramsay",
        posicion: { fila: 3, columna: 18 }
    },

    // Período 4 - Primeros elementos
    {
        numero: 19,
        simbolo: "K",
        nombre: "Potasio",
        masa: 39.098,
        grupo: 1,
        periodo: 4,
        familia: "metales-alcalinos",
        estado: "solido",
        electronegatividad: 0.82,
        radioAtomico: 243,
        configuracionElectronica: "[Ar] 4s¹",
        usos: ["Fertilizantes", "Medicina", "Fuegos artificiales", "Jabones", "Alimentación"],
        datoCurioso: "Es esencial para la vida, regulando el equilibrio de fluidos y la función nerviosa.",
        descubrimiento: "1807 por Sir Humphry Davy",
        posicion: { fila: 4, columna: 1 }
    },
    {
        numero: 20,
        simbolo: "Ca",
        nombre: "Calcio",
        masa: 40.078,
        grupo: 2,
        periodo: 4,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 1.00,
        radioAtomico: 194,
        configuracionElectronica: "[Ar] 4s²",
        usos: ["Huesos y dientes", "Cemento", "Metalurgia", "Queso", "Suplementos"],
        datoCurioso: "Es el quinto elemento más abundante en la corteza terrestre y vital para la vida.",
        descubrimiento: "1808 por Sir Humphry Davy",
        posicion: { fila: 4, columna: 2 }
    },

    // Metales de transición del período 4
    {
        numero: 21,
        simbolo: "Sc",
        nombre: "Escandio",
        masa: 44.956,
        grupo: 3,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.36,
        radioAtomico: 184,
        configuracionElectronica: "[Ar] 3d¹ 4s²",
        usos: ["Aleaciones aeroespaciales", "Lámparas de alta intensidad", "Equipos deportivos"],
        datoCurioso: "Fue predicho por Mendeleev antes de su descubrimiento como 'eka-boro'.",
        descubrimiento: "1879 por Lars Fredrik Nilson",
        posicion: { fila: 4, columna: 3 }
    },
    {
        numero: 22,
        simbolo: "Ti",
        nombre: "Titanio",
        masa: 47.867,
        grupo: 4,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.54,
        radioAtomico: 176,
        configuracionElectronica: "[Ar] 3d² 4s²",
        usos: ["Aeronáutica", "Implantes médicos", "Pigmentos", "Equipos deportivos", "Joyería"],
        datoCurioso: "Tiene la mayor resistencia a la corrosión de todos los metales y es biocompatible.",
        descubrimiento: "1791 por William Gregor",
        posicion: { fila: 4, columna: 4 }
    },
    {
        numero: 23,
        simbolo: "V",
        nombre: "Vanadio",
        masa: 50.942,
        grupo: 5,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.63,
        radioAtomico: 171,
        configuracionElectronica: "[Ar] 3d³ 4s²",
        usos: ["Aleaciones de acero", "Catalizadores", "Baterías", "Herramientas"],
        datoCurioso: "Sus compuestos muestran una amplia gama de colores brillantes.",
        descubrimiento: "1801 por Andrés Manuel del Río",
        posicion: { fila: 4, columna: 5 }
    },
    {
        numero: 24,
        simbolo: "Cr",
        nombre: "Cromo",
        masa: 51.996,
        grupo: 6,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.66,
        radioAtomico: 166,
        configuracionElectronica: "[Ar] 3d⁵ 4s¹",
        usos: ["Acero inoxidable", "Cromado", "Pigmentos", "Curtido de pieles"],
        datoCurioso: "Su nombre deriva del griego 'chroma' (color) por los vivos colores de sus compuestos.",
        descubrimiento: "1797 por Louis-Nicolas Vauquelin",
        posicion: { fila: 4, columna: 6 }
    },
    {
        numero: 25,
        simbolo: "Mn",
        nombre: "Manganeso",
        masa: 54.938,
        grupo: 7,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.55,
        radioAtomico: 161,
        configuracionElectronica: "[Ar] 3d⁵ 4s²",
        usos: ["Producción de acero", "Baterías", "Fertilizantes", "Permanganato"],
        datoCurioso: "Es esencial para la fotosíntesis y el metabolismo del oxígeno en las plantas.",
        descubrimiento: "1774 por Johan Gottlieb Gahn",
        posicion: { fila: 4, columna: 7 }
    },
    {
        numero: 26,
        simbolo: "Fe",
        nombre: "Hierro",
        masa: 55.845,
        grupo: 8,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.83,
        radioAtomico: 156,
        configuracionElectronica: "[Ar] 3d⁶ 4s²",
        usos: ["Acero", "Construcción", "Hemoglobina", "Imanes", "Herramientas"],
        datoCurioso: "Es el elemento más abundante en la Tierra por masa y el núcleo del planeta es principalmente hierro.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 4, columna: 8 }
    },
    {
        numero: 27,
        simbolo: "Co",
        nombre: "Cobalto",
        masa: 58.933,
        grupo: 9,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.88,
        radioAtomico: 152,
        configuracionElectronica: "[Ar] 3d⁷ 4s²",
        usos: ["Aleaciones", "Imanes permanentes", "Baterías", "Pigmentos azules", "Medicina nuclear"],
        datoCurioso: "Es esencial para la vitamina B12 y da el color azul característico al vidrio y la cerámica.",
        descubrimiento: "1735 por Georg Brandt",
        posicion: { fila: 4, columna: 9 }
    },
    {
        numero: 28,
        simbolo: "Ni",
        nombre: "Níquel",
        masa: 58.693,
        grupo: 10,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.91,
        radioAtomico: 149,
        configuracionElectronica: "[Ar] 3d⁸ 4s²",
        usos: ["Acero inoxidable", "Monedas", "Baterías", "Catalizadores", "Aleaciones"],
        datoCurioso: "Los meteoritos contienen níquel-hierro y fueron la primera fuente de níquel puro conocida.",
        descubrimiento: "1751 por Axel Fredrik Cronstedt",
        posicion: { fila: 4, columna: 10 }
    },
    {
        numero: 29,
        simbolo: "Cu",
        nombre: "Cobre",
        masa: 63.546,
        grupo: 11,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.90,
        radioAtomico: 145,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s¹",
        usos: ["Cables eléctricos", "Tuberías", "Monedas", "Aleaciones", "Antimicrobiano"],
        datoCurioso: "Fue uno de los primeros metales utilizados por los humanos, hace más de 10,000 años.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 4, columna: 11 }
    },
    {
        numero: 30,
        simbolo: "Zn",
        nombre: "Zinc",
        masa: 65.380,
        grupo: 12,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.65,
        radioAtomico: 142,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s²",
        usos: ["Galvanizado", "Aleaciones", "Baterías", "Suplementos", "Protector solar"],
        datoCurioso: "Es esencial para más de 100 enzimas en el cuerpo humano y la curación de heridas.",
        descubrimiento: "1746 por Andreas Sigismund Marggraf",
        posicion: { fila: 4, columna: 12 }
    },

    // Continuando período 4
    {
        numero: 31,
        simbolo: "Ga",
        nombre: "Galio",
        masa: 69.723,
        grupo: 13,
        periodo: 4,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.81,
        radioAtomico: 136,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p¹",
        usos: ["Semiconductores", "LEDs", "Termómetros de alta temperatura", "Aleaciones"],
        datoCurioso: "Se derrite en la mano (punto de fusión 29.8°C) y fue predicho por Mendeleev.",
        descubrimiento: "1875 por Paul-Émile Lecoq de Boisbaudran",
        posicion: { fila: 4, columna: 13 }
    },
    {
        numero: 32,
        simbolo: "Ge",
        nombre: "Germanio",
        masa: 72.640,
        grupo: 14,
        periodo: 4,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.01,
        radioAtomico: 125,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p²",
        usos: ["Semiconductores", "Fibra óptica", "Detectores de radiación", "Catalizadores"],
        datoCurioso: "Su descubrimiento validó las predicciones de Mendeleev sobre la tabla periódica.",
        descubrimiento: "1886 por Clemens Winkler",
        posicion: { fila: 4, columna: 14 }
    },
    {
        numero: 33,
        simbolo: "As",
        nombre: "Arsénico",
        masa: 74.922,
        grupo: 15,
        periodo: 4,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.18,
        radioAtomico: 114,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p³",
        usos: ["Semiconductores", "Preservante de madera", "Aleaciones", "Medicina"],
        datoCurioso: "Conocido como veneno desde la antigüedad, pero también se usa en medicina contra la leucemia.",
        descubrimiento: "1250 por Albertus Magnus",
        posicion: { fila: 4, columna: 15 }
    },
    {
        numero: 34,
        simbolo: "Se",
        nombre: "Selenio",
        masa: 78.960,
        grupo: 16,
        periodo: 4,
        familia: "no-metales",
        estado: "solido",
        electronegatividad: 2.55,
        radioAtomico: 103,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁴",
        usos: ["Fotoceldas", "Suplementos", "Vidrio", "Champús anticaspa", "Rectificadores"],
        datoCurioso: "Es tóxico en grandes cantidades pero esencial como micronutriente para la salud.",
        descubrimiento: "1817 por Jöns Jacob Berzelius",
        posicion: { fila: 4, columna: 16 }
    },
    {
        numero: 35,
        simbolo: "Br",
        nombre: "Bromo",
        masa: 79.904,
        grupo: 17,
        periodo: 4,
        familia: "halogenos",
        estado: "liquido",
        electronegatividad: 2.96,
        radioAtomico: 94,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁵",
        usos: ["Retardantes de llama", "Medicina", "Fotografía", "Fumigantes", "Tintes"],
        datoCurioso: "Es uno de los dos únicos elementos líquidos a temperatura ambiente (junto con el mercurio).",
        descubrimiento: "1826 por Antoine Jérôme Balard",
        posicion: { fila: 4, columna: 17 }
    },
    {
        numero: 36,
        simbolo: "Kr",
        nombre: "Kriptón",
        masa: 83.798,
        grupo: 18,
        periodo: 4,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: 3.00,
        radioAtomico: 88,
        configuracionElectronica: "[Ar] 3d¹⁰ 4s² 4p⁶",
        usos: ["Lámparas fluorescentes", "Láser", "Ventanas aislantes", "Estándar de longitud"],
        datoCurioso: "Se usó para definir el metro estándar desde 1960 hasta 1983.",
        descubrimiento: "1898 por William Ramsay y Morris Travers",
        posicion: { fila: 4, columna: 18 }
    },

    // Período 5 - Completo
    {
        numero: 37,
        simbolo: "Rb",
        nombre: "Rubidio",
        masa: 85.468,
        grupo: 1,
        periodo: 5,
        familia: "metales-alcalinos",
        estado: "solido",
        electronegatividad: 0.82,
        radioAtomico: 265,
        configuracionElectronica: "[Kr] 5s¹",
        usos: ["Relojes atómicos", "Investigación", "Catalizadores", "Vidrio especial"],
        datoCurioso: "Se inflama espontáneamente en el aire y fue el primer elemento descubierto por espectroscopía.",
        descubrimiento: "1861 por Robert Bunsen y Gustav Kirchhoff",
        posicion: { fila: 5, columna: 1 }
    },
    {
        numero: 38,
        simbolo: "Sr",
        nombre: "Estroncio",
        masa: 87.620,
        grupo: 2,
        periodo: 5,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 0.95,
        radioAtomico: 219,
        configuracionElectronica: "[Kr] 5s²",
        usos: ["Fuegos artificiales", "Medicina nuclear", "Imanes de ferrita", "Vidrio para televisores"],
        datoCurioso: "Da una llama roja carmesí brillante y se usa en medicina para tratar cáncer de huesos.",
        descubrimiento: "1790 por Adair Crawford",
        posicion: { fila: 5, columna: 2 }
    },
    {
        numero: 39,
        simbolo: "Y",
        nombre: "Itrio",
        masa: 88.906,
        grupo: 3,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.22,
        radioAtomico: 212,
        configuracionElectronica: "[Kr] 4d¹ 5s²",
        usos: ["Aleaciones", "Láseres", "Superconductores", "Televisores LED"],
        datoCurioso: "Fue nombrado en honor al pueblo sueco Ytterby, que también dio nombre a otros tres elementos.",
        descubrimiento: "1794 por Johan Gadolin",
        posicion: { fila: 5, columna: 3 }
    },
    {
        numero: 40,
        simbolo: "Zr",
        nombre: "Circonio",
        masa: 91.224,
        grupo: 4,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.33,
        radioAtomico: 206,
        configuracionElectronica: "[Kr] 4d² 5s²",
        usos: ["Reactores nucleares", "Joyería", "Implantes médicos", "Cerámicas refractarias"],
        datoCurioso: "Es extremadamente resistente a la corrosión y casi transparente a los neutrones.",
        descubrimiento: "1789 por Martin Heinrich Klaproth",
        posicion: { fila: 5, columna: 4 }
    },
    {
        numero: 41,
        simbolo: "Nb",
        nombre: "Niobio",
        masa: 92.906,
        grupo: 5,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.60,
        radioAtomico: 198,
        configuracionElectronica: "[Kr] 4d⁴ 5s¹",
        usos: ["Superconductores", "Aleaciones de acero", "Joyería", "Motores de cohetes"],
        datoCurioso: "Tiene el punto de fusión más alto de todos los metales del grupo 5.",
        descubrimiento: "1801 por Charles Hatchett",
        posicion: { fila: 5, columna: 5 }
    },
    {
        numero: 42,
        simbolo: "Mo",
        nombre: "Molibdeno",
        masa: 95.960,
        grupo: 6,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.16,
        radioAtomico: 190,
        configuracionElectronica: "[Kr] 4d⁵ 5s¹",
        usos: ["Aleaciones de acero", "Catalizadores", "Lubricantes", "Pigmentos"],
        datoCurioso: "Es esencial para todas las formas de vida y se encuentra en muchas enzimas.",
        descubrimiento: "1778 por Carl Wilhelm Scheele",
        posicion: { fila: 5, columna: 6 }
    },
    {
        numero: 43,
        simbolo: "Tc",
        nombre: "Tecnecio",
        masa: 98.000,
        grupo: 7,
        periodo: 5,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: 1.90,
        radioAtomico: 183,
        configuracionElectronica: "[Kr] 4d⁵ 5s²",
        usos: ["Medicina nuclear", "Radiografías", "Investigación científica"],
        datoCurioso: "Fue el primer elemento sintético producido artificialmente en 1937.",
        descubrimiento: "1937 por Emilio Segrè y Carlo Perrier",
        posicion: { fila: 5, columna: 7 }
    },
    {
        numero: 44,
        simbolo: "Ru",
        nombre: "Rutenio",
        masa: 101.070,
        grupo: 8,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.20,
        radioAtomico: 178,
        configuracionElectronica: "[Kr] 4d⁷ 5s¹",
        usos: ["Catalizadores", "Contactos eléctricos", "Aleaciones", "Medicina"],
        datoCurioso: "Es uno de los metales del grupo del platino y extremadamente raro en la Tierra.",
        descubrimiento: "1844 por Karl Ernst Claus",
        posicion: { fila: 5, columna: 8 }
    },
    {
        numero: 45,
        simbolo: "Rh",
        nombre: "Rodio",
        masa: 102.906,
        grupo: 9,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.28,
        radioAtomico: 173,
        configuracionElectronica: "[Kr] 4d⁸ 5s¹",
        usos: ["Catalizadores automotrices", "Joyería", "Espejos", "Detectores de neutrones"],
        datoCurioso: "Es uno de los metales más caros del mundo, más valioso que el oro y el platino.",
        descubrimiento: "1803 por William Hyde Wollaston",
        posicion: { fila: 5, columna: 9 }
    },
    {
        numero: 46,
        simbolo: "Pd",
        nombre: "Paladio",
        masa: 106.420,
        grupo: 10,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.20,
        radioAtomico: 169,
        configuracionElectronica: "[Kr] 4d¹⁰",
        usos: ["Catalizadores", "Joyería", "Odontología", "Electrónica"],
        datoCurioso: "Puede absorber hasta 900 veces su volumen en hidrógeno gaseoso.",
        descubrimiento: "1803 por William Hyde Wollaston",
        posicion: { fila: 5, columna: 10 }
    },
    {
        numero: 47,
        simbolo: "Ag",
        nombre: "Plata",
        masa: 107.868,
        grupo: 11,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.93,
        radioAtomico: 165,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s¹",
        usos: ["Joyería", "Monedas", "Fotografía", "Espejos", "Antibacteriano"],
        datoCurioso: "Tiene la mayor conductividad eléctrica y térmica de todos los elementos.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 5, columna: 11 }
    },
    {
        numero: 48,
        simbolo: "Cd",
        nombre: "Cadmio",
        masa: 112.411,
        grupo: 12,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.69,
        radioAtomico: 161,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s²",
        usos: ["Baterías", "Pigmentos", "Galvanoplastia", "Reactores nucleares"],
        datoCurioso: "Es extremadamente tóxico y carcinógeno, pero esencial en algunas aplicaciones industriales.",
        descubrimiento: "1817 por Friedrich Stromeyer",
        posicion: { fila: 5, columna: 12 }
    },
    {
        numero: 49,
        simbolo: "In",
        nombre: "Indio",
        masa: 114.818,
        grupo: 13,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.78,
        radioAtomico: 156,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p¹",
        usos: ["Pantallas táctiles", "Soldaduras", "Aleaciones", "Semiconductores"],
        datoCurioso: "Es tan blando que se puede rayar con la uña y emite un sonido característico al doblarse.",
        descubrimiento: "1863 por Ferdinand Reich y Hieronymus Theodor Richter",
        posicion: { fila: 5, columna: 13 }
    },
    {
        numero: 50,
        simbolo: "Sn",
        nombre: "Estaño",
        masa: 118.710,
        grupo: 14,
        periodo: 5,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.96,
        radioAtomico: 145,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p²",
        usos: ["Soldadura", "Revestimiento de latas", "Aleaciones", "Vidrio flotado"],
        datoCurioso: "A bajas temperaturas sufre la 'peste del estaño', convirtiéndose en polvo gris.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 5, columna: 14 }
    },
    {
        numero: 51,
        simbolo: "Sb",
        nombre: "Antimonio",
        masa: 121.760,
        grupo: 15,
        periodo: 5,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.05,
        radioAtomico: 133,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p³",
        usos: ["Retardantes de llama", "Aleaciones", "Semiconductores", "Medicina"],
        datoCurioso: "Era usado por los antiguos egipcios como cosmético para los ojos (kohl).",
        descubrimiento: "Prehistórico",
        posicion: { fila: 5, columna: 15 }
    },
    {
        numero: 52,
        simbolo: "Te",
        nombre: "Telurio",
        masa: 127.600,
        grupo: 16,
        periodo: 5,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.10,
        radioAtomico: 123,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁴",
        usos: ["Aleaciones", "Semiconductores", "Termoelectricidad", "Catalizadores"],
        datoCurioso: "Es más raro que el oro en la corteza terrestre y da mal aliento cuando se ingiere.",
        descubrimiento: "1782 por Franz-Joseph Müller von Reichenstein",
        posicion: { fila: 5, columna: 16 }
    },
    {
        numero: 53,
        simbolo: "I",
        nombre: "Yodo",
        masa: 126.904,
        grupo: 17,
        periodo: 5,
        familia: "halogenos",
        estado: "solido",
        electronegatividad: 2.66,
        radioAtomico: 115,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁵",
        usos: ["Desinfectante", "Sal yodada", "Medicina", "Tintes", "Fotografía"],
        datoCurioso: "Es esencial para la tiroides y sublima directamente de sólido a gas a temperatura ambiente.",
        descubrimiento: "1811 por Bernard Courtois",
        posicion: { fila: 5, columna: 17 }
    },
    {
        numero: 54,
        simbolo: "Xe",
        nombre: "Xenón",
        masa: 131.293,
        grupo: 18,
        periodo: 5,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: 2.60,
        radioAtomico: 108,
        configuracionElectronica: "[Kr] 4d¹⁰ 5s² 5p⁶",
        usos: ["Lámparas de xenón", "Anestesia", "Propulsión espacial", "Detectores"],
        datoCurioso: "Aunque es un gas noble, puede formar algunos compuestos químicos bajo condiciones extremas.",
        descubrimiento: "1898 por William Ramsay y Morris Travers",
        posicion: { fila: 5, columna: 18 }
    },

    // Período 6 - Completo
    {
        numero: 55,
        simbolo: "Cs",
        nombre: "Cesio",
        masa: 132.905,
        grupo: 1,
        periodo: 6,
        familia: "metales-alcalinos",
        estado: "solido",
        electronegatividad: 0.79,
        radioAtomico: 298,
        configuracionElectronica: "[Xe] 6s¹",
        usos: ["Relojes atómicos", "Fotoceldas", "Catalizadores", "Fluidos de perforación"],
        datoCurioso: "Es el metal más reactivo y se usa para definir el segundo en el tiempo atómico.",
        descubrimiento: "1860 por Robert Bunsen y Gustav Kirchhoff",
        posicion: { fila: 6, columna: 1 }
    },
    {
        numero: 56,
        simbolo: "Ba",
        nombre: "Bario",
        masa: 137.327,
        grupo: 2,
        periodo: 6,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 0.89,
        radioAtomico: 253,
        configuracionElectronica: "[Xe] 6s²",
        usos: ["Rayos X", "Fuegos artificiales", "Medicina", "Perforación petrolífera"],
        datoCurioso: "Produce una llama verde brillante y se usa en medicina como contraste para rayos X.",
        descubrimiento: "1808 por Sir Humphry Davy",
        posicion: { fila: 6, columna: 2 }
    },
    {
        numero: 57,
        simbolo: "La",
        nombre: "Lantano",
        masa: 138.905,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.10,
        radioAtomico: 240,
        configuracionElectronica: "[Xe] 5d¹ 6s²",
        usos: ["Aleaciones", "Óptica", "Catalizadores", "Baterías híbridas"],
        datoCurioso: "Es el elemento que da nombre a la serie de los lantánidos y se oxida rápidamente al aire.",
        descubrimiento: "1839 por Carl Gustaf Mosander",
        posicion: { fila: 8, columna: 4 }
    },

    // Serie de los Lantánidos (58-71)
    {
        numero: 58,
        simbolo: "Ce",
        nombre: "Cerio",
        masa: 140.116,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.12,
        radioAtomico: 235,
        configuracionElectronica: "[Xe] 4f¹ 5d¹ 6s²",
        usos: ["Catalizadores", "Aleaciones", "Lentes", "Encendedores"],
        datoCurioso: "Es el lantánido más abundante y se usa en convertidores catalíticos de automóviles.",
        descubrimiento: "1803 por Jöns Jakob Berzelius y Wilhelm Hisinger",
        posicion: { fila: 8, columna: 5 }
    },
    {
        numero: 59,
        simbolo: "Pr",
        nombre: "Praseodimio",
        masa: 140.908,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.13,
        radioAtomico: 239,
        configuracionElectronica: "[Xe] 4f³ 6s²",
        usos: ["Imanes", "Aleaciones", "Vidrio", "Cerámicas"],
        datoCurioso: "Su nombre significa 'gemelo verde' por los colores verdes de sus sales.",
        descubrimiento: "1885 por Carl Auer von Welsbach",
        posicion: { fila: 8, columna: 6 }
    },
    {
        numero: 60,
        simbolo: "Nd",
        nombre: "Neodimio",
        masa: 144.242,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.14,
        radioAtomico: 229,
        configuracionElectronica: "[Xe] 4f⁴ 6s²",
        usos: ["Imanes permanentes", "Láseres", "Vidrio", "Catalizadores"],
        datoCurioso: "Forma los imanes permanentes más potentes conocidos y es esencial en turbinas eólicas.",
        descubrimiento: "1885 por Carl Auer von Welsbach",
        posicion: { fila: 8, columna: 7 }
    },
    {
        numero: 61,
        simbolo: "Pm",
        nombre: "Prometio",
        masa: 145.000,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "sintetico",
        electronegatividad: 1.13,
        radioAtomico: 205,
        configuracionElectronica: "[Xe] 4f⁵ 6s²",
        usos: ["Investigación nuclear", "Marcapasos", "Pintura luminosa"],
        datoCurioso: "Es el único lantánido radioactivo y fue el último elemento descubierto de forma natural.",
        descubrimiento: "1945 por Jacob A. Marinsky, Lawrence E. Glendenin y Charles D. Coryell",
        posicion: { fila: 8, columna: 8 }
    },
    {
        numero: 62,
        simbolo: "Sm",
        nombre: "Samario",
        masa: 150.360,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.17,
        radioAtomico: 238,
        configuracionElectronica: "[Xe] 4f⁶ 6s²",
        usos: ["Imanes", "Reactores nucleares", "Catalizadores", "Láseres"],
        datoCurioso: "Forma aleaciones que mantienen sus propiedades magnéticas a altas temperaturas.",
        descubrimiento: "1879 por Paul-Émile Lecoq de Boisbaudran",
        posicion: { fila: 8, columna: 9 }
    },
    {
        numero: 63,
        simbolo: "Eu",
        nombre: "Europio",
        masa: 151.964,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.20,
        radioAtomico: 231,
        configuracionElectronica: "[Xe] 4f⁷ 6s²",
        usos: ["Fósforos", "Televisores", "Detectores de falsificación", "Medicina nuclear"],
        datoCurioso: "Es el lantánido más reactivo y produce una fluorescencia roja distintiva.",
        descubrimiento: "1901 por Eugène-Anatole Demarçay",
        posicion: { fila: 8, columna: 10 }
    },
    {
        numero: 64,
        simbolo: "Gd",
        nombre: "Gadolinio",
        masa: 157.250,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.20,
        radioAtomico: 233,
        configuracionElectronica: "[Xe] 4f⁷ 5d¹ 6s²",
        usos: ["Medicina nuclear", "Reactores nucleares", "Aleaciones", "Resonancia magnética"],
        datoCurioso: "Tiene la mayor sección transversal de absorción de neutrones de todos los elementos.",
        descubrimiento: "1880 por Jean Charles Galissard de Marignac",
        posicion: { fila: 8, columna: 11 }
    },
    {
        numero: 65,
        simbolo: "Tb",
        nombre: "Terbio",
        masa: 158.925,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.20,
        radioAtomico: 225,
        configuracionElectronica: "[Xe] 4f⁹ 6s²",
        usos: ["Fósforos", "Aleaciones", "Dispositivos magnetoópticos", "Actuadores"],
        datoCurioso: "Fue nombrado en honor a Ytterby, Suecia, como otros tres elementos (Y, Yb, Er).",
        descubrimiento: "1843 por Carl Gustaf Mosander",
        posicion: { fila: 8, columna: 12 }
    },
    {
        numero: 66,
        simbolo: "Dy",
        nombre: "Disprosio",
        masa: 162.500,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.22,
        radioAtomico: 228,
        configuracionElectronica: "[Xe] 4f¹⁰ 6s²",
        usos: ["Imanes", "Discos duros", "Reactores nucleares", "Aleaciones"],
        datoCurioso: "Su nombre significa 'difícil de obtener' debido a la dificultad de su separación.",
        descubrimiento: "1886 por Paul-Émile Lecoq de Boisbaudran",
        posicion: { fila: 8, columna: 13 }
    },
    {
        numero: 67,
        simbolo: "Ho",
        nombre: "Holmio",
        masa: 164.930,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.23,
        radioAtomico: 226,
        configuracionElectronica: "[Xe] 4f¹¹ 6s²",
        usos: ["Imanes", "Láseres", "Aleaciones", "Calibración magnética"],
        datoCurioso: "Tiene las propiedades magnéticas más extremas de todos los elementos naturales.",
        descubrimiento: "1878 por Per Teodor Cleve",
        posicion: { fila: 8, columna: 14 }
    },
    {
        numero: 68,
        simbolo: "Er",
        nombre: "Erbio",
        masa: 167.259,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.24,
        radioAtomico: 226,
        configuracionElectronica: "[Xe] 4f¹² 6s²",
        usos: ["Fibra óptica", "Láseres", "Aleaciones", "Vidrio rosado"],
        datoCurioso: "Es esencial para las comunicaciones por fibra óptica de internet.",
        descubrimiento: "1843 por Carl Gustaf Mosander",
        posicion: { fila: 8, columna: 15 }
    },
    {
        numero: 69,
        simbolo: "Tm",
        nombre: "Tulio",
        masa: 168.934,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.25,
        radioAtomico: 222,
        configuracionElectronica: "[Xe] 4f¹³ 6s²",
        usos: ["Rayos X portátiles", "Láseres", "Investigación científica"],
        datoCurioso: "Es el segundo lantánido más raro después del prometio.",
        descubrimiento: "1879 por Per Teodor Cleve",
        posicion: { fila: 8, columna: 16 }
    },
    {
        numero: 70,
        simbolo: "Yb",
        nombre: "Iterbio",
        masa: 173.054,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.10,
        radioAtomico: 222,
        configuracionElectronica: "[Xe] 4f¹⁴ 6s²",
        usos: ["Aleaciones", "Láseres", "Medicina nuclear", "Relojes atómicos"],
        datoCurioso: "También nombrado por Ytterby, completando los cuatro elementos de este pueblo sueco.",
        descubrimiento: "1878 por Jean Charles Galissard de Marignac",
        posicion: { fila: 8, columna: 17 }
    },
    {
        numero: 71,
        simbolo: "Lu",
        nombre: "Lutecio",
        masa: 174.967,
        grupo: 3,
        periodo: 6,
        familia: "lantanidos",
        estado: "solido",
        electronegatividad: 1.27,
        radioAtomico: 217,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹ 6s²",
        usos: ["Medicina nuclear", "Catalizadores", "Investigación científica"],
        datoCurioso: "Es el último y más caro de los lantánidos, y el más duro de la serie.",
        descubrimiento: "1907 por Georges Urbain, Carl Auer von Welsbach y Charles James",
        posicion: { fila: 8, columna: 18 }
    },
    {
        numero: 72,
        simbolo: "Hf",
        nombre: "Hafnio",
        masa: 178.490,
        grupo: 4,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.30,
        radioAtomico: 208,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d² 6s²",
        usos: ["Reactores nucleares", "Filamentos", "Electrodos", "Superaleaciones"],
        datoCurioso: "Fue el penúltimo elemento natural en ser descubierto debido a su similitud con el circonio.",
        descubrimiento: "1923 por Dirk Coster y George de Hevesy",
        posicion: { fila: 6, columna: 4 }
    },
    {
        numero: 73,
        simbolo: "Ta",
        nombre: "Tantalio",
        masa: 180.948,
        grupo: 5,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.50,
        radioAtomico: 200,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d³ 6s²",
        usos: ["Capacitores", "Implantes médicos", "Herramientas", "Aleaciones"],
        datoCurioso: "Es prácticamente inmune a la corrosión y su nombre viene del rey mitológico Tántalo.",
        descubrimiento: "1802 por Anders Gustaf Ekeberg",
        posicion: { fila: 6, columna: 5 }
    },
    {
        numero: 74,
        simbolo: "W",
        nombre: "Wolframio",
        masa: 183.840,
        grupo: 6,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.36,
        radioAtomico: 193,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d⁴ 6s²",
        usos: ["Filamentos de bombillas", "Herramientas", "Blindajes", "Aleaciones"],
        datoCurioso: "Tiene el punto de fusión más alto de todos los elementos (3695°C).",
        descubrimiento: "1783 por Juan José Elhuyar y Fausto Elhuyar",
        posicion: { fila: 6, columna: 6 }
    },
    {
        numero: 75,
        simbolo: "Re",
        nombre: "Renio",
        masa: 186.207,
        grupo: 7,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.90,
        radioAtomico: 188,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d⁵ 6s²",
        usos: ["Catalizadores", "Termopares", "Filamentos", "Motores de avión"],
        datoCurioso: "Fue el último elemento natural estable en ser descubierto.",
        descubrimiento: "1925 por Ida Noddack, Walter Noddack y Otto Berg",
        posicion: { fila: 6, columna: 7 }
    },
    {
        numero: 76,
        simbolo: "Os",
        nombre: "Osmio",
        masa: 190.230,
        grupo: 8,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.20,
        radioAtomico: 185,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d⁶ 6s²",
        usos: ["Aleaciones", "Plumas estilográficas", "Catalizadores", "Contactos eléctricos"],
        datoCurioso: "Es el elemento más denso de la tabla periódica y su tetróxido es extremadamente tóxico.",
        descubrimiento: "1803 por Smithson Tennant",
        posicion: { fila: 6, columna: 8 }
    },
    {
        numero: 77,
        simbolo: "Ir",
        nombre: "Iridio",
        masa: 192.217,
        grupo: 9,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.20,
        radioAtomico: 180,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d⁷ 6s²",
        usos: ["Aleaciones", "Crisoles", "Contactos eléctricos", "Marcapasos"],
        datoCurioso: "Es el metal más resistente a la corrosión y se encuentra en alta concentración en la capa de arcilla del impacto que mató a los dinosaurios.",
        descubrimiento: "1803 por Smithson Tennant",
        posicion: { fila: 6, columna: 9 }
    },
    {
        numero: 78,
        simbolo: "Pt",
        nombre: "Platino",
        masa: 195.084,
        grupo: 10,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.28,
        radioAtomico: 177,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
        usos: ["Joyería", "Catalizadores", "Medicina", "Electrodos", "Estándar de masa"],
        datoCurioso: "Es 30 veces más raro que el oro y fue usado por las civilizaciones precolombinas.",
        descubrimiento: "1735 por Antonio de Ulloa",
        posicion: { fila: 6, columna: 10 }
    },

    // Período 6 - Elementos importantes
    {
        numero: 79,
        simbolo: "Au",
        nombre: "Oro",
        masa: 196.967,
        grupo: 11,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.54,
        radioAtomico: 174,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
        usos: ["Joyería", "Electrónica", "Medicina", "Monedas", "Estándar monetario"],
        datoCurioso: "Es prácticamente indestructible y no se oxida, manteniendo su brillo eternamente.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 6, columna: 11 }
    },
    {
        numero: 80,
        simbolo: "Hg",
        nombre: "Mercurio",
        masa: 200.590,
        grupo: 12,
        periodo: 6,
        familia: "metales-transicion",
        estado: "liquido",
        electronegatividad: 2.00,
        radioAtomico: 171,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
        usos: ["Termómetros", "Lámparas fluorescentes", "Amalgamas dentales", "Interruptores"],
        datoCurioso: "Es el único metal líquido a temperatura ambiente y extremadamente tóxico.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 6, columna: 12 }
    },
    {
        numero: 81,
        simbolo: "Tl",
        nombre: "Talio",
        masa: 204.383,
        grupo: 13,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 1.62,
        radioAtomico: 156,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
        usos: ["Detectores de radiación", "Vidrio óptico", "Semiconductores", "Medicina nuclear"],
        datoCurioso: "Es extremadamente tóxico, conocido como 'polvo de herencia' por su uso histórico como veneno.",
        descubrimiento: "1861 por William Crookes",
        posicion: { fila: 6, columna: 13 }
    },
    {
        numero: 82,
        simbolo: "Pb",
        nombre: "Plomo",
        masa: 207.200,
        grupo: 14,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.33,
        radioAtomico: 154,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
        usos: ["Baterías", "Blindaje de radiación", "Municiones", "Soldadura"],
        datoCurioso: "Era usado por los romanos en tuberías, pero su toxicidad puede haber contribuido a la caída del imperio.",
        descubrimiento: "Prehistórico",
        posicion: { fila: 6, columna: 14 }
    },
    {
        numero: 83,
        simbolo: "Bi",
        nombre: "Bismuto",
        masa: 208.980,
        grupo: 15,
        periodo: 6,
        familia: "metales-transicion",
        estado: "solido",
        electronegatividad: 2.02,
        radioAtomico: 143,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
        usos: ["Medicina", "Cosméticos", "Aleaciones", "Detectores de fuego"],
        datoCurioso: "Es el elemento más pesado que no es radioactivo de forma natural y forma cristales iridiscentes.",
        descubrimiento: "1753 por Claude François Geoffroy",
        posicion: { fila: 6, columna: 15 }
    },
    {
        numero: 84,
        simbolo: "Po",
        nombre: "Polonio",
        masa: 209.000,
        grupo: 16,
        periodo: 6,
        familia: "metaloides",
        estado: "solido",
        electronegatividad: 2.00,
        radioAtomico: 135,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
        usos: ["Fuentes de radiación", "Eliminadores de estática", "Investigación nuclear"],
        datoCurioso: "Fue descubierto por Marie Curie y es extremadamente radioactivo y tóxico.",
        descubrimiento: "1898 por Marie y Pierre Curie",
        posicion: { fila: 6, columna: 16 }
    },
    {
        numero: 85,
        simbolo: "At",
        nombre: "Ástato",
        masa: 210.000,
        grupo: 17,
        periodo: 6,
        familia: "halogenos",
        estado: "sintetico",
        electronegatividad: 2.20,
        radioAtomico: 127,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
        usos: ["Investigación científica", "Medicina nuclear"],
        datoCurioso: "Es el elemento más raro en la corteza terrestre, con menos de 30 gramos en total.",
        descubrimiento: "1940 por Dale R. Corson, Kenneth Ross MacKenzie y Emilio Segrè",
        posicion: { fila: 6, columna: 17 }
    },
    {
        numero: 86,
        simbolo: "Rn",
        nombre: "Radón",
        masa: 222.000,
        grupo: 18,
        periodo: 6,
        familia: "gases-nobles",
        estado: "gas",
        electronegatividad: 2.20,
        radioAtomico: 120,
        configuracionElectronica: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
        usos: ["Investigación médica", "Estudios de terremotos"],
        datoCurioso: "Es radioactivo y la segunda causa principal de cáncer de pulmón después del tabaco.",
        descubrimiento: "1900 por Friedrich Ernst Dorn",
        posicion: { fila: 6, columna: 18 }
    },

    // Período 7 - Completo
    {
        numero: 87,
        simbolo: "Fr",
        nombre: "Francio",
        masa: 223.000,
        grupo: 1,
        periodo: 7,
        familia: "metales-alcalinos",
        estado: "sintetico",
        electronegatividad: 0.70,
        radioAtomico: 348,
        configuracionElectronica: "[Rn] 7s¹",
        usos: ["Investigación científica"],
        datoCurioso: "Es el elemento natural más raro y radioactivo, con menos de 30 gramos en toda la Tierra.",
        descubrimiento: "1939 por Marguerite Perey",
        posicion: { fila: 7, columna: 1 }
    },
    {
        numero: 88,
        simbolo: "Ra",
        nombre: "Radio",
        masa: 226.000,
        grupo: 2,
        periodo: 7,
        familia: "metales-alcalinoterreos",
        estado: "solido",
        electronegatividad: 0.90,
        radioAtomico: 283,
        configuracionElectronica: "[Rn] 7s²",
        usos: ["Medicina nuclear", "Investigación científica", "Pintura luminosa"],
        datoCurioso: "Fue descubierto por Marie Curie y brillaba en la oscuridad debido a su radiactividad.",
        descubrimiento: "1898 por Marie y Pierre Curie",
        posicion: { fila: 7, columna: 2 }
    },
    {
        numero: 89,
        simbolo: "Ac",
        nombre: "Actinio",
        masa: 227.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.10,
        radioAtomico: 260,
        configuracionElectronica: "[Rn] 6d¹ 7s²",
        usos: ["Investigación científica", "Medicina nuclear"],
        datoCurioso: "Da nombre a la serie de los actínidos y brilla con una luz azul en la oscuridad.",
        descubrimiento: "1899 por André-Louis Debierne",
        posicion: { fila: 9, columna: 4 }
    },

    // Serie de los Actínidos (90-103)
    {
        numero: 90,
        simbolo: "Th",
        nombre: "Torio",
        masa: 232.038,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "solido",
        electronegatividad: 1.30,
        radioAtomico: 237,
        configuracionElectronica: "[Rn] 6d² 7s²",
        usos: ["Energía nuclear", "Aleaciones", "Lámparas de gas", "Lentes"],
        datoCurioso: "Es más abundante que el uranio y se considera una fuente de energía nuclear del futuro.",
        descubrimiento: "1828 por Jöns Jakob Berzelius",
        posicion: { fila: 9, columna: 5 }
    },
    {
        numero: 91,
        simbolo: "Pa",
        nombre: "Protactinio",
        masa: 231.036,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.50,
        radioAtomico: 243,
        configuracionElectronica: "[Rn] 5f² 6d¹ 7s²",
        usos: ["Investigación científica", "Datación radioactiva"],
        datoCurioso: "Es extremadamente tóxico y uno de los elementos más raros y peligrosos conocidos.",
        descubrimiento: "1913 por Kasimir Fajans y Otto Göhring",
        posicion: { fila: 9, columna: 6 }
    },
    {
        numero: 93,
        simbolo: "Np",
        nombre: "Neptunio",
        masa: 237.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.36,
        radioAtomico: 221,
        configuracionElectronica: "[Rn] 5f⁴ 6d¹ 7s²",
        usos: ["Investigación nuclear", "Detectores de neutrones"],
        datoCurioso: "Fue el primer elemento transuránico sintetizado y nombrado por el planeta Neptuno.",
        descubrimiento: "1940 por Edwin McMillan y Philip Abelson",
        posicion: { fila: 9, columna: 8 }
    },
    {
        numero: 94,
        simbolo: "Pu",
        nombre: "Plutonio",
        masa: 244.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.28,
        radioAtomico: 243,
        configuracionElectronica: "[Rn] 5f⁶ 7s²",
        usos: ["Armas nucleares", "Energía nuclear", "Marcapasos", "Sondas espaciales"],
        datoCurioso: "Es uno de los materiales más tóxicos conocidos, unos pocos microgramos pueden ser letales.",
        descubrimiento: "1940 por Glenn T. Seaborg y equipo",
        posicion: { fila: 9, columna: 9 }
    },
    {
        numero: 95,
        simbolo: "Am",
        nombre: "Americio",
        masa: 243.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 244,
        configuracionElectronica: "[Rn] 5f⁷ 7s²",
        usos: ["Detectores de humo", "Investigación nuclear", "Medicina nuclear"],
        datoCurioso: "Se encuentra en millones de detectores de humo domésticos alrededor del mundo.",
        descubrimiento: "1944 por Glenn T. Seaborg y equipo",
        posicion: { fila: 9, columna: 10 }
    },
    {
        numero: 96,
        simbolo: "Cm",
        nombre: "Curio",
        masa: 247.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 245,
        configuracionElectronica: "[Rn] 5f⁷ 6d¹ 7s²",
        usos: ["Investigación nuclear", "Fuentes de radiación", "Sondas espaciales"],
        datoCurioso: "Nombrado en honor a Marie y Pierre Curie, brillaba visiblemente en la oscuridad.",
        descubrimiento: "1944 por Glenn T. Seaborg y equipo",
        posicion: { fila: 9, columna: 11 }
    },
    {
        numero: 97,
        simbolo: "Bk",
        nombre: "Berkelio",
        masa: 247.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 244,
        configuracionElectronica: "[Rn] 5f⁹ 7s²",
        usos: ["Investigación científica", "Síntesis de elementos más pesados"],
        datoCurioso: "Nombrado por Berkeley, California, donde fue descubierto en el ciclotrón.",
        descubrimiento: "1949 por Glenn T. Seaborg y equipo",
        posicion: { fila: 9, columna: 12 }
    },
    {
        numero: 98,
        simbolo: "Cf",
        nombre: "Californio",
        masa: 251.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 245,
        configuracionElectronica: "[Rn] 5f¹⁰ 7s²",
        usos: ["Fuentes de neutrones", "Medicina nuclear", "Análisis de metales"],
        datoCurioso: "Un gramo cuesta más de 25 millones de dólares y emite 170 millones de neutrones por minuto.",
        descubrimiento: "1950 por Glenn T. Seaborg y equipo",
        posicion: { fila: 9, columna: 13 }
    },
    {
        numero: 99,
        simbolo: "Es",
        nombre: "Einsteinio",
        masa: 252.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 245,
        configuracionElectronica: "[Rn] 5f¹¹ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Albert Einstein, fue descubierto en los restos de una prueba nuclear.",
        descubrimiento: "1952 por Albert Ghiorso y equipo",
        posicion: { fila: 9, columna: 14 }
    },
    {
        numero: 100,
        simbolo: "Fm",
        nombre: "Fermio",
        masa: 257.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 245,
        configuracionElectronica: "[Rn] 5f¹² 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Enrico Fermi, también fue descubierto en una explosión nuclear.",
        descubrimiento: "1952 por Albert Ghiorso y equipo",
        posicion: { fila: 9, columna: 15 }
    },
    {
        numero: 101,
        simbolo: "Md",
        nombre: "Mendelevio",
        masa: 258.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 246,
        configuracionElectronica: "[Rn] 5f¹³ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Dmitri Mendeleev, creador de la tabla periódica.",
        descubrimiento: "1955 por Albert Ghiorso y equipo",
        posicion: { fila: 9, columna: 16 }
    },
    {
        numero: 102,
        simbolo: "No",
        nombre: "Nobelio",
        masa: 259.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 246,
        configuracionElectronica: "[Rn] 5f¹⁴ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Alfred Nobel, su descubrimiento fue controvertido por años.",
        descubrimiento: "1957 por Albert Ghiorso y equipo",
        posicion: { fila: 9, columna: 17 }
    },
    {
        numero: 103,
        simbolo: "Lr",
        nombre: "Lawrencio",
        masa: 262.000,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "sintetico",
        electronegatividad: 1.30,
        radioAtomico: 246,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Ernest Lawrence, inventor del ciclotrón, último de los actínidos.",
        descubrimiento: "1961 por Albert Ghiorso y equipo",
        posicion: { fila: 9, columna: 18 }
    },

    // Elementos super pesados transactínidos (104-118)
    {
        numero: 104,
        simbolo: "Rf",
        nombre: "Rutherfordio",
        masa: 267.000,
        grupo: 4,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d² 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Ernest Rutherford, existe solo por milisegundos.",
        descubrimiento: "1964 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 4 }
    },
    {
        numero: 105,
        simbolo: "Db",
        nombre: "Dubnio",
        masa: 268.000,
        grupo: 5,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d³ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado por la ciudad de Dubna, Rusia, donde fue sintetizado.",
        descubrimiento: "1968 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 5 }
    },
    {
        numero: 106,
        simbolo: "Sg",
        nombre: "Seaborgio",
        masa: 271.000,
        grupo: 6,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁴ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Glenn T. Seaborg, pionero en elementos sintéticos.",
        descubrimiento: "1974 por Laboratorio Nacional Lawrence Berkeley",
        posicion: { fila: 7, columna: 6 }
    },
    {
        numero: 107,
        simbolo: "Bh",
        nombre: "Bohrio",
        masa: 272.000,
        grupo: 7,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁵ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Niels Bohr, físico danés y modelo atómico.",
        descubrimiento: "1981 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 7 }
    },
    {
        numero: 108,
        simbolo: "Hs",
        nombre: "Hassio",
        masa: 277.000,
        grupo: 8,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁶ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado por el estado alemán de Hesse, donde está el instituto GSI.",
        descubrimiento: "1984 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 8 }
    },
    {
        numero: 109,
        simbolo: "Mt",
        nombre: "Meitnerio",
        masa: 276.000,
        grupo: 9,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁷ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Lise Meitner, física austriaca pionera en fisión nuclear.",
        descubrimiento: "1982 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 9 }
    },
    {
        numero: 110,
        simbolo: "Ds",
        nombre: "Darmstadtio",
        masa: 281.000,
        grupo: 10,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁸ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado por Darmstadt, Alemania, ciudad cerca del instituto GSI.",
        descubrimiento: "1994 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 10 }
    },
    {
        numero: 111,
        simbolo: "Rg",
        nombre: "Roentgenio",
        masa: 280.000,
        grupo: 11,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d⁹ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Wilhelm Röntgen, descubridor de los rayos X.",
        descubrimiento: "1994 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 11 }
    },
    {
        numero: 112,
        simbolo: "Cn",
        nombre: "Copernicio",
        masa: 285.000,
        grupo: 12,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Nicolás Copérnico, astrónomo del modelo heliocéntrico.",
        descubrimiento: "1996 por GSI Helmholtzzentrum für Schwerionenforschung",
        posicion: { fila: 7, columna: 12 }
    },
    {
        numero: 113,
        simbolo: "Nh",
        nombre: "Nihonio",
        masa: 284.000,
        grupo: 13,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
        usos: ["Investigación científica"],
        datoCurioso: "Primer elemento sintetizado en Asia, su nombre deriva de 'Nihon' (Japón).",
        descubrimiento: "2004 por RIKEN (Japón)",
        posicion: { fila: 7, columna: 13 }
    },
    {
        numero: 114,
        simbolo: "Fl",
        nombre: "Flerovio",
        masa: 289.000,
        grupo: 14,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor a Georgy Flyorov, físico nuclear soviético.",
        descubrimiento: "1999 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 14 }
    },
    {
        numero: 115,
        simbolo: "Mc",
        nombre: "Moscovio",
        masa: 288.000,
        grupo: 15,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado por la región de Moscú, donde está el instituto de investigación.",
        descubrimiento: "2003 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 15 }
    },
    {
        numero: 116,
        simbolo: "Lv",
        nombre: "Livermorio",
        masa: 293.000,
        grupo: 16,
        periodo: 7,
        familia: "metales-transicion",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado en honor al Laboratorio Nacional Lawrence Livermore.",
        descubrimiento: "2000 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 16 }
    },
    {
        numero: 117,
        simbolo: "Ts",
        nombre: "Téneso",
        masa: 294.000,
        grupo: 17,
        periodo: 7,
        familia: "halogenos",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
        usos: ["Investigación científica"],
        datoCurioso: "Nombrado por Tennessee, estado donde está el Laboratorio Nacional Oak Ridge.",
        descubrimiento: "2010 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 17 }
    },

    // Uranio - elemento actínido ubicado correctamente
    {
        numero: 92,
        simbolo: "U",
        nombre: "Uranio",
        masa: 238.029,
        grupo: 3,
        periodo: 7,
        familia: "actinidos",
        estado: "solido",
        electronegatividad: 1.38,
        radioAtomico: 186,
        configuracionElectronica: "[Rn] 5f³ 6d¹ 7s²",
        usos: ["Energía nuclear", "Armas nucleares", "Blindaje", "Datación radioactiva"],
        datoCurioso: "Es el elemento natural más pesado y puede sostener una reacción en cadena nuclear.",
        descubrimiento: "1789 por Martin Heinrich Klaproth",
        posicion: { fila: 9, columna: 7 }
    },
    {
        numero: 118,
        simbolo: "Og",
        nombre: "Oganesón",
        masa: 294.000,
        grupo: 18,
        periodo: 7,
        familia: "gases-nobles",
        estado: "sintetico",
        electronegatividad: null,
        radioAtomico: null,
        configuracionElectronica: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
        usos: ["Investigación científica"],
        datoCurioso: "Es el elemento más pesado conocido y existe solo por milisegundos antes de desintegrarse.",
        descubrimiento: "2002 por Instituto Conjunto para Investigación Nuclear",
        posicion: { fila: 7, columna: 18 }
    }
];

// Funciones auxiliares para el manejo de datos
const ElementosData = {
    // Obtener todos los elementos
    todos: () => elementosQuimicos,

    // Buscar elemento por número atómico
    porNumero: (numero) => elementosQuimicos.find(el => el.numero === numero),

    // Buscar elemento por símbolo
    porSimbolo: (simbolo) => elementosQuimicos.find(el => el.simbolo.toLowerCase() === simbolo.toLowerCase()),

    // Buscar elemento por nombre
    porNombre: (nombre) => elementosQuimicos.find(el => el.nombre.toLowerCase().includes(nombre.toLowerCase())),

    // Filtrar por familia
    porFamilia: (familia) => elementosQuimicos.filter(el => el.familia === familia),

    // Filtrar por estado
    porEstado: (estado) => elementosQuimicos.filter(el => el.estado === estado),

    // Filtrar por período
    porPeriodo: (periodo) => elementosQuimicos.filter(el => el.periodo === periodo),

    // Filtrar por grupo
    porGrupo: (grupo) => elementosQuimicos.filter(el => el.grupo === grupo),

    // Buscar por texto (nombre, símbolo o número)
    buscar: (texto) => {
        const termino = texto.toLowerCase();
        return elementosQuimicos.filter(el =>
            el.nombre.toLowerCase().includes(termino) ||
            el.simbolo.toLowerCase().includes(termino) ||
            el.numero.toString().includes(termino)
        );
    },

    // Filtrar por rango de masa atómica
    porRangoMasa: (min, max) => elementosQuimicos.filter(el => el.masa >= min && el.masa <= max),

    // Filtrar por rango de radio atómico
    porRangoRadio: (min, max) => elementosQuimicos.filter(el => el.radioAtomico && el.radioAtomico >= min && el.radioAtomico <= max),

    // Obtener elemento aleatorio
    aleatorio: () => elementosQuimicos[Math.floor(Math.random() * elementosQuimicos.length)],

    // Obtener familias únicas
    familias: () => [...new Set(elementosQuimicos.map(el => el.familia))],

    // Obtener estados únicos
    estados: () => [...new Set(elementosQuimicos.map(el => el.estado))],

    // Estadísticas
    estadisticas: () => ({
        total: elementosQuimicos.length,
        solidos: elementosQuimicos.filter(el => el.estado === 'solido').length,
        liquidos: elementosQuimicos.filter(el => el.estado === 'liquido').length,
        gases: elementosQuimicos.filter(el => el.estado === 'gas').length,
        sinteticos: elementosQuimicos.filter(el => el.estado === 'sintetico').length,
        masaPromedio: elementosQuimicos.reduce((sum, el) => sum + el.masa, 0) / elementosQuimicos.length
    })
};

// Exportar para uso en otros módulos
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { elementosQuimicos, ElementosData };
}