const glosarioData = [
    {
        id: 1,
        termino: "Átomo",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "La unidad más pequeña de un elemento químico que mantiene sus propiedades.",
        definicionCompleta: "El átomo es la unidad constituyente más pequeña de la materia ordinaria que tiene las propiedades de un elemento químico. Está formado por un núcleo con protones y neutrones, rodeado por electrones en orbitales.",
        formula: "Número atómico (Z) = número de protones",
        ejemplo: "Un átomo de hidrógeno tiene 1 protón, mientras que un átomo de carbono tiene 6 protones.",
        relacionados: ["Molécula", "Electrón", "Protón", "Neutrón"]
    },
    {
        id: 2,
        termino: "Molécula",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Grupo de átomos unidos químicamente que forma la unidad más pequeña de un compuesto.",
        definicionCompleta: "Una molécula es un grupo eléctricamente neutro de dos o más átomos unidos por enlaces químicos. Las moléculas se distinguen de los iones por su carga eléctrica neutra.",
        formula: "H₂O = 2 átomos de hidrógeno + 1 átomo de oxígeno",
        ejemplo: "El agua (H₂O) es una molécula formada por dos átomos de hidrógeno y uno de oxígeno.",
        relacionados: ["Átomo", "Enlace químico", "Compuesto"]
    },
    {
        id: 3,
        termino: "Velocidad",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Magnitud física que expresa el desplazamiento de un objeto por unidad de tiempo.",
        definicionCompleta: "La velocidad es una magnitud vectorial que relaciona el cambio de posición con el tiempo. Se mide en metros por segundo (m/s) en el Sistema Internacional.",
        formula: "v = Δx/Δt (velocidad = desplazamiento/tiempo)",
        ejemplo: "Un coche que recorre 100 km en 2 horas tiene una velocidad media de 50 km/h.",
        relacionados: ["Aceleración", "Desplazamiento", "Rapidez"]
    },
    {
        id: 4,
        termino: "Aceleración",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Cambio de velocidad de un objeto con respecto al tiempo.",
        definicionCompleta: "La aceleración es la tasa de cambio de la velocidad de un objeto con respecto al tiempo. Es una magnitud vectorial con unidades de m/s².",
        formula: "a = Δv/Δt (aceleración = cambio de velocidad/tiempo)",
        ejemplo: "La gravedad terrestre produce una aceleración de 9,8 m/s² en los objetos en caída libre.",
        relacionados: ["Velocidad", "Fuerza", "Masa"]
    },
    {
        id: 5,
        termino: "Fuerza",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Interacción que modifica el movimiento de un cuerpo o lo deforma.",
        definicionCompleta: "La fuerza es una magnitud vectorial que describe la interacción entre dos cuerpos. Según la Segunda Ley de Newton, la fuerza es igual a la masa por la aceleración.",
        formula: "F = m × a (Fuerza = masa × aceleración)",
        ejemplo: "Para mover una caja de 10 kg con una aceleración de 2 m/s² se necesita una fuerza de 20 N.",
        relacionados: ["Masa", "Aceleración", "Newton", "Peso"]
    },
    {
        id: 6,
        termino: "Energía",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Capacidad de un sistema para realizar trabajo o producir cambios.",
        definicionCompleta: "La energía es una propiedad de los objetos que puede ser transferida a otros objetos o convertida en diferentes formas. Se conserva en sistemas aislados según el principio de conservación de la energía.",
        formula: "E = mc² (energía-masa de Einstein)",
        ejemplo: "Un objeto en movimiento tiene energía cinética, mientras que un objeto elevado tiene energía potencial.",
        relacionados: ["Trabajo", "Potencia", "Energía cinética", "Energía potencial"]
    },
    {
        id: 7,
        termino: "pH",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Escala que mide la acidez o alcalinidad de una solución.",
        definicionCompleta: "El pH es una medida de la concentración de iones hidrógeno en una solución. La escala va de 0 a 14, donde 7 es neutro, menor que 7 es ácido y mayor que 7 es básico.",
        formula: "pH = -log[H⁺]",
        ejemplo: "El jugo de limón tiene pH ~2 (ácido), el agua pura pH 7 (neutro), y el jabón pH ~11 (básico).",
        relacionados: ["Ácido", "Base", "Neutralización", "Ion"]
    },
    {
        id: 8,
        termino: "Enlace químico",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Fuerza que mantiene unidos a los átomos en las moléculas y compuestos.",
        definicionCompleta: "El enlace químico es la fuerza de atracción entre átomos que permite la formación de sustancias compuestas. Puede ser iónico, covalente o metálico.",
        formula: "Tipos: iónico (transferencia e⁻), covalente (compartición e⁻), metálico (mar de e⁻)",
        ejemplo: "El NaCl tiene enlace iónico, el H₂O enlace covalente, y el Fe enlace metálico.",
        relacionados: ["Átomo", "Molécula", "Electrón", "Valencia"]
    },
    {
        id: 9,
        termino: "Onda",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Perturbación que se propaga transportando energía sin transportar materia.",
        definicionCompleta: "Una onda es una perturbación que se propaga a través del espacio y el tiempo, transportando energía sin transporte neto de materia. Se caracteriza por su amplitud, frecuencia y longitud de onda.",
        formula: "v = λ × f (velocidad = longitud de onda × frecuencia)",
        ejemplo: "El sonido es una onda mecánica, mientras que la luz es una onda electromagnética.",
        relacionados: ["Frecuencia", "Longitud de onda", "Amplitud", "Periodo"]
    },
    {
        id: 10,
        termino: "Presión",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Fuerza ejercida por unidad de superficie.",
        definicionCompleta: "La presión es la magnitud que relaciona la fuerza aplicada con la superficie sobre la cual se distribuye. Se mide en pascales (Pa) en el Sistema Internacional.",
        formula: "P = F/A (Presión = Fuerza/Área)",
        ejemplo: "La presión atmosférica al nivel del mar es aproximadamente 101.325 Pa.",
        relacionados: ["Fuerza", "Área", "Pascal", "Atmósfera"]
    },
    {
        id: 11,
        termino: "Reacción química",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Proceso en el que unas sustancias se transforman en otras diferentes.",
        definicionCompleta: "Una reacción química es un proceso termodinámico en el cual una o más sustancias (reactivos) se transforman, cambiando su estructura molecular y sus enlaces, para formar otras sustancias (productos).",
        formula: "Reactivos → Productos",
        ejemplo: "2H₂ + O₂ → 2H₂O (formación de agua a partir de hidrógeno y oxígeno)",
        relacionados: ["Reactivo", "Producto", "Catalizador", "Equilibrio químico"]
    },
    {
        id: 12,
        termino: "Masa",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Cantidad de materia que contiene un cuerpo.",
        definicionCompleta: "La masa es una magnitud escalar que expresa la cantidad de materia de un cuerpo. Es invariante y no depende de la posición del cuerpo en el espacio.",
        formula: "m = ρ × V (masa = densidad × volumen)",
        ejemplo: "Un kilogramo es la masa de un litro de agua a 4°C.",
        relacionados: ["Peso", "Densidad", "Volumen", "Inercia"]
    },
    {
        id: 13,
        termino: "Electrón",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Partícula subatómica con carga negativa que orbita el núcleo atómico.",
        definicionCompleta: "El electrón es una partícula elemental con carga eléctrica negativa. Los electrones orbitan el núcleo atómico en niveles de energía y son responsables de las propiedades químicas de los elementos.",
        formula: "Carga del electrón: -1,602 × 10⁻¹⁹ C",
        ejemplo: "Los electrones de valencia determinan cómo un átomo forma enlaces químicos.",
        relacionados: ["Átomo", "Protón", "Neutrón", "Orbital"]
    },
    {
        id: 14,
        termino: "Trabajo",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Energía transferida cuando una fuerza mueve un objeto.",
        definicionCompleta: "El trabajo es la energía transferida hacia o desde un objeto mediante la aplicación de una fuerza a lo largo de un desplazamiento. Se mide en julios (J).",
        formula: "W = F × d × cos(θ) (Trabajo = Fuerza × distancia × coseno del ángulo)",
        ejemplo: "Levantar un libro de 1 kg a 1 metro de altura requiere aproximadamente 10 J de trabajo.",
        relacionados: ["Energía", "Fuerza", "Potencia", "Julio"]
    },
    {
        id: 15,
        termino: "Mol",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Unidad de cantidad de sustancia que contiene 6,022 × 10²³ partículas.",
        definicionCompleta: "El mol es la unidad del Sistema Internacional que se usa para medir la cantidad de sustancia. Un mol contiene exactamente 6,02214076 × 10²³ entidades elementales (número de Avogadro).",
        formula: "n = m/M (moles = masa/masa molar)",
        ejemplo: "Un mol de agua (18 g) contiene 6,022 × 10²³ moléculas de H₂O.",
        relacionados: ["Número de Avogadro", "Masa molar", "Molécula"]
    },
    {
        id: 16,
        termino: "Temperatura",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Magnitud que mide el grado de agitación térmica de las partículas.",
        definicionCompleta: "La temperatura es una magnitud escalar relacionada con la energía cinética promedio de las partículas de un sistema. Se mide en kelvin (K), grados Celsius (°C) o Fahrenheit (°F).",
        formula: "K = °C + 273,15",
        ejemplo: "El agua hierve a 100°C (373,15 K) y se congela a 0°C (273,15 K) a presión normal.",
        relacionados: ["Calor", "Energía térmica", "Termómetro"]
    },
    {
        id: 17,
        termino: "Oxidación",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Proceso químico en el que una sustancia pierde electrones.",
        definicionCompleta: "La oxidación es una reacción química donde un átomo, ion o molécula pierde electrones, aumentando su estado de oxidación. Siempre ocurre junto con la reducción.",
        formula: "Fe → Fe²⁺ + 2e⁻ (oxidación del hierro)",
        ejemplo: "El hierro se oxida al aire formando óxido (herrumbre).",
        relacionados: ["Reducción", "Redox", "Electrón", "Corrosión"]
    },
    {
        id: 18,
        termino: "Vector",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Magnitud física que tiene módulo, dirección y sentido.",
        definicionCompleta: "Un vector es un segmento orientado que representa magnitudes físicas con módulo (tamaño), dirección y sentido. Se representa con una flecha y se opera según el álgebra vectorial.",
        formula: "|v| = √(vₓ² + vᵧ² + vᵢ²) (módulo del vector)",
        ejemplo: "La velocidad, fuerza y aceleración son magnitudes vectoriales.",
        relacionados: ["Escalar", "Magnitud", "Componentes", "Resultante"]
    },
    {
        id: 19,
        termino: "Densidad",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Relación entre la masa y el volumen de una sustancia.",
        definicionCompleta: "La densidad es una magnitud escalar que relaciona la masa de un cuerpo con el volumen que ocupa. Se expresa en kg/m³ en el Sistema Internacional.",
        formula: "ρ = m/V (densidad = masa/volumen)",
        ejemplo: "El agua tiene una densidad de 1000 kg/m³, mientras que el hierro tiene 7874 kg/m³.",
        relacionados: ["Masa", "Volumen", "Flotabilidad"]
    },
    {
        id: 20,
        termino: "Catalizador",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Sustancia que acelera una reacción química sin consumirse.",
        definicionCompleta: "Un catalizador es una sustancia que aumenta la velocidad de una reacción química disminuyendo la energía de activación, sin ser consumido en el proceso.",
        formula: "Ea(con catalizador) < Ea(sin catalizador)",
        ejemplo: "Las enzimas son catalizadores biológicos que aceleran las reacciones en los seres vivos.",
        relacionados: ["Reacción química", "Energía de activación", "Enzima"]
    },
    {
        id: 21,
        termino: "Entropía",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Magnitud termodinámica que mide el grado de desorden de un sistema.",
        definicionCompleta: "La entropía es una función de estado que mide el grado de desorden molecular de un sistema. Según la segunda ley de la termodinámica, la entropía del universo siempre aumenta.",
        formula: "ΔS = Q/T (cambio de entropía)",
        ejemplo: "El hielo al derretirse aumenta su entropía porque las moléculas pasan de un estado ordenado a uno más desordenado.",
        relacionados: ["Termodinámica", "Desorden", "Segunda ley"]
    },
    {
        id: 22,
        termino: "Equilibrio químico",
        categoria: "quimica",
        nivel: "avanzado",
        definicionCorta: "Estado donde las velocidades de reacción directa e inversa son iguales.",
        definicionCompleta: "El equilibrio químico es el estado de un sistema reaccionante en el que no se observan cambios a medida que transcurre el tiempo, porque las velocidades de reacción directa e inversa son iguales.",
        formula: "Kc = [productos]/[reactivos] (constante de equilibrio)",
        ejemplo: "N₂ + 3H₂ ⇌ 2NH₃ (síntesis de amoníaco en equilibrio)",
        relacionados: ["Reacción reversible", "Le Chatelier", "Constante de equilibrio"]
    },
    {
        id: 23,
        termino: "Campo eléctrico",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Región del espacio donde una carga eléctrica experimenta una fuerza.",
        definicionCompleta: "El campo eléctrico es un campo físico que describe la interacción entre cuerpos con carga eléctrica. Se define como la fuerza por unidad de carga.",
        formula: "E = F/q = k·Q/r² (campo eléctrico)",
        ejemplo: "Un campo eléctrico de 1000 N/C ejerce una fuerza de 1 N sobre una carga de 0,001 C.",
        relacionados: ["Carga eléctrica", "Fuerza eléctrica", "Potencial eléctrico"]
    },
    {
        id: 24,
        termino: "Isótopo",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Átomos del mismo elemento con diferente número de neutrones.",
        definicionCompleta: "Los isótopos son variantes de un elemento químico que tienen el mismo número de protones pero diferente número de neutrones, y por tanto, diferente masa atómica.",
        formula: "A = Z + N (masa atómica = protones + neutrones)",
        ejemplo: "El carbono-12 y carbono-14 son isótopos del carbono con 6 y 8 neutrones respectivamente.",
        relacionados: ["Átomo", "Neutrón", "Masa atómica", "Radiactividad"]
    },
    {
        id: 25,
        termino: "Momentum",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Cantidad de movimiento de un cuerpo, producto de su masa por velocidad.",
        definicionCompleta: "El momentum o cantidad de movimiento es una magnitud vectorial que relaciona la masa y velocidad de un cuerpo. Se conserva en sistemas aislados.",
        formula: "p = m × v (momentum = masa × velocidad)",
        ejemplo: "Una pelota de 0,5 kg moviéndose a 10 m/s tiene un momentum de 5 kg·m/s.",
        relacionados: ["Impulso", "Conservación del momentum", "Colisión"]
    },
    {
        id: 26,
        termino: "Protón",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Partícula subatómica con carga positiva en el núcleo atómico.",
        definicionCompleta: "El protón es una partícula elemental con carga eléctrica positiva. Determina el número atómico del elemento.",
        formula: "Carga del protón: +1,602 × 10⁻¹⁹ C",
        ejemplo: "El hidrógeno tiene 1 protón, el helio 2 protones.",
        relacionados: ["Átomo", "Electrón", "Neutrón", "Núcleo"]
    },
    {
        id: 27,
        termino: "Neutrón",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Partícula subatómica sin carga en el núcleo atómico.",
        definicionCompleta: "El neutrón es una partícula subatómica eléctricamente neutra. Su número determina los isótopos.",
        formula: "Masa del neutrón ≈ masa del protón",
        ejemplo: "El carbono-12 tiene 6 neutrones, el carbono-14 tiene 8.",
        relacionados: ["Protón", "Isótopo", "Núcleo", "Radiactividad"]
    },
    {
        id: 28,
        termino: "Ion",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Átomo o molécula con carga eléctrica por ganancia o pérdida de electrones.",
        definicionCompleta: "Un ion es un átomo que ha ganado o perdido electrones, adquiriendo carga neta.",
        formula: "Catión: carga +, Anión: carga -",
        ejemplo: "Na⁺ (catión sodio), Cl⁻ (anión cloruro).",
        relacionados: ["Electrón", "Ionización", "Sal", "Enlace iónico"]
    },
    {
        id: 29,
        termino: "Covalente",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Enlace químico donde se comparten electrones entre átomos.",
        definicionCompleta: "El enlace covalente se forma cuando dos átomos comparten pares de electrones.",
        formula: "Compartición de pares electrónicos",
        ejemplo: "H₂O, CO₂, CH₄ tienen enlaces covalentes.",
        relacionados: ["Enlace químico", "Molécula", "Electrón", "Valencia"]
    },
    {
        id: 30,
        termino: "Iónico",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Enlace químico por transferencia de electrones entre átomos.",
        definicionCompleta: "El enlace iónico se forma por atracción electrostática entre iones de cargas opuestas.",
        formula: "Metal + No metal → Sal iónica",
        ejemplo: "NaCl, CaF₂, MgO son compuestos iónicos.",
        relacionados: ["Ion", "Electrón", "Sal", "Cristal"]
    },
    {
        id: 31,
        termino: "Ácido",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Sustancia que libera iones H⁺ en solución acuosa.",
        definicionCompleta: "Un ácido es una sustancia que aumenta la concentración de iones hidrógeno en agua.",
        formula: "HA → H⁺ + A⁻",
        ejemplo: "HCl, H₂SO₄, CH₃COOH son ácidos.",
        relacionados: ["Base", "pH", "Ion", "Neutralización"]
    },
    {
        id: 32,
        termino: "Base",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Sustancia que libera iones OH⁻ en solución acuosa.",
        definicionCompleta: "Una base es una sustancia que aumenta la concentración de iones hidróxido en agua.",
        formula: "BOH → B⁺ + OH⁻",
        ejemplo: "NaOH, Ca(OH)₂, NH₃ son bases.",
        relacionados: ["Ácido", "pH", "Neutralización", "Alcalino"]
    },
    {
        id: 33,
        termino: "Calor",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Energía en tránsito debido a diferencia de temperatura.",
        definicionCompleta: "El calor es la transferencia de energía térmica entre sistemas a diferentes temperaturas.",
        formula: "Q = mcΔT (calor específico)",
        ejemplo: "El agua absorbe calor para hervir a 100°C.",
        relacionados: ["Temperatura", "Energía", "Termómetro", "Joule"]
    },
    {
        id: 34,
        termino: "Potencia",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Energía transferida por unidad de tiempo.",
        definicionCompleta: "La potencia mide la rapidez con que se realiza trabajo o se transfiere energía.",
        formula: "P = W/t = E/t (Potencia = Trabajo/tiempo)",
        ejemplo: "Una bombilla de 60W consume 60 julios por segundo.",
        relacionados: ["Trabajo", "Energía", "Watt", "Tiempo"]
    },
    {
        id: 35,
        termino: "Corriente eléctrica",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Flujo de cargas eléctricas a través de un conductor.",
        definicionCompleta: "La corriente eléctrica es el movimiento ordenado de cargas eléctricas por un material.",
        formula: "I = Q/t (Corriente = Carga/tiempo)",
        ejemplo: "Una corriente de 2A significa 2 coulombs por segundo.",
        relacionados: ["Voltaje", "Resistencia", "Ley de Ohm", "Circuito"]
    },
    {
        id: 36,
        termino: "Voltaje",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Diferencia de potencial eléctrico entre dos puntos.",
        definicionCompleta: "El voltaje es la energía por unidad de carga entre dos puntos de un circuito.",
        formula: "V = W/Q (Voltaje = Trabajo/Carga)",
        ejemplo: "Una pila AA tiene 1,5V de diferencia de potencial.",
        relacionados: ["Corriente eléctrica", "Resistencia", "Potencial", "Volt"]
    },
    {
        id: 37,
        termino: "Resistencia eléctrica",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Oposición al flujo de corriente eléctrica.",
        definicionCompleta: "La resistencia eléctrica mide la dificultad que opone un material al paso de corriente.",
        formula: "R = V/I (Ley de Ohm)",
        ejemplo: "Una resistencia de 10Ω limita la corriente en un circuito.",
        relacionados: ["Corriente eléctrica", "Voltaje", "Ley de Ohm", "Ohmio"]
    },
    {
        id: 38,
        termino: "Magnético",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Campo de fuerza creado por imanes o cargas en movimiento.",
        definicionCompleta: "El campo magnético es una región donde se manifiestan fuerzas magnéticas.",
        formula: "F = q(v × B) (Fuerza de Lorentz)",
        ejemplo: "La Tierra tiene un campo magnético que orienta las brújulas.",
        relacionados: ["Imán", "Campo eléctrico", "Electromagnético", "Tesla"]
    },
    {
        id: 39,
        termino: "Gravitación",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Fuerza de atracción universal entre masas.",
        definicionCompleta: "La gravitación es la fuerza atractiva que actúa entre todos los objetos con masa.",
        formula: "F = G(m₁m₂)/r² (Ley de Newton)",
        ejemplo: "La Luna orbita la Tierra por la fuerza gravitacional.",
        relacionados: ["Masa", "Peso", "Órbita", "Newton"]
    },
    {
        id: 40,
        termino: "Radiación",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Emisión de energía en forma de ondas o partículas.",
        definicionCompleta: "La radiación es la propagación de energía a través del espacio.",
        formula: "E = hf (energía del fotón)",
        ejemplo: "El Sol emite radiación electromagnética visible.",
        relacionados: ["Electromagnético", "Fotón", "Luz", "Energía"]
    },
    {
        id: 41,
        termino: "Cristal",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Sólido con estructura atómica ordenada y repetitiva.",
        definicionCompleta: "Un cristal tiene átomos organizados en patrones geométricos regulares tridimensionales.",
        formula: "Red cristalina periódica",
        ejemplo: "La sal, el cuarzo y el diamante forman cristales.",
        relacionados: ["Iónico", "Enlace químico", "Sólido", "Estructura"]
    },
    {
        id: 42,
        termino: "Solución",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Mezcla homogénea de soluto disuelto en un solvente.",
        definicionCompleta: "Una solución es una mezcla donde el soluto se dispersa uniformemente en el solvente.",
        formula: "Concentración = soluto/solvente",
        ejemplo: "Agua con sal, agua con azúcar son soluciones.",
        relacionados: ["Concentración", "Solubilidad", "Mezcla", "Disolver"]
    },
    {
        id: 43,
        termino: "Concentración",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Cantidad de soluto presente en una solución.",
        definicionCompleta: "La concentración expresa la proporción de soluto respecto al solvente o solución total.",
        formula: "M = moles soluto/litros solución",
        ejemplo: "Una solución 1M tiene 1 mol de soluto por litro.",
        relacionados: ["Solución", "Molaridad", "Mol", "Dilución"]
    },
    {
        id: 44,
        termino: "Velocidad de reacción",
        categoria: "quimica",
        nivel: "avanzado",
        definicionCorta: "Rapidez con que se consumen reactivos o forman productos.",
        definicionCompleta: "La velocidad de reacción mide el cambio de concentración por unidad de tiempo.",
        formula: "v = Δ[concentración]/Δt",
        ejemplo: "La combustión es más rápida que la oxidación del hierro.",
        relacionados: ["Catalizador", "Reacción química", "Cinética", "Equilibrio químico"]
    },
    {
        id: 45,
        termino: "Enzima",
        categoria: "quimica",
        nivel: "avanzado",
        definicionCorta: "Catalizador biológico que acelera reacciones químicas.",
        definicionCompleta: "Las enzimas son proteínas que catalizan reacciones bioquímicas específicas.",
        formula: "E + S ⇌ ES → E + P",
        ejemplo: "La amilasa descompone el almidón en azúcares.",
        relacionados: ["Catalizador", "Proteína", "Velocidad de reacción", "Bioquímica"]
    },
    {
        id: 46,
        termino: "Orbital",
        categoria: "quimica",
        nivel: "avanzado",
        definicionCorta: "Región del espacio donde es probable encontrar un electrón.",
        definicionCompleta: "Los orbitales son funciones matemáticas que describen la distribución electrónica.",
        formula: "s, p, d, f (tipos de orbitales)",
        ejemplo: "El orbital 1s del hidrógeno es esférico.",
        relacionados: ["Electrón", "Átomo", "Configuración electrónica", "Cuántico"]
    },
    {
        id: 47,
        termino: "Polaridad",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Distribución desigual de cargas en una molécula.",
        definicionCompleta: "La polaridad surge cuando hay diferencia de electronegatividad entre átomos enlazados.",
        formula: "δ+ y δ- (cargas parciales)",
        ejemplo: "H₂O es polar, CO₂ es no polar.",
        relacionados: ["Enlace químico", "Electronegatividad", "Dipolo", "Solubilidad"]
    },
    {
        id: 48,
        termino: "Frecuencia",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Número de oscilaciones completas por unidad de tiempo.",
        definicionCompleta: "La frecuencia mide cuántas veces se repite un fenómeno periódico por segundo.",
        formula: "f = 1/T (frecuencia = 1/periodo)",
        ejemplo: "La corriente doméstica tiene frecuencia de 50 Hz.",
        relacionados: ["Onda", "Periodo", "Hertz", "Longitud de onda"]
    },
    {
        id: 49,
        termino: "Amplitud",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Máximo desplazamiento de una onda desde su posición de equilibrio.",
        definicionCompleta: "La amplitud determina la intensidad o energía transportada por la onda.",
        formula: "A = desplazamiento máximo",
        ejemplo: "Mayor amplitud de sonido = mayor volumen.",
        relacionados: ["Onda", "Energía", "Intensidad", "Oscilación"]
    },
    {
        id: 50,
        termino: "Reflexión",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Cambio de dirección de una onda al chocar con una superficie.",
        definicionCompleta: "La reflexión ocurre cuando una onda rebota al encontrar un obstáculo.",
        formula: "Ángulo incidencia = Ángulo reflexión",
        ejemplo: "Los espejos reflejan la luz, el eco refleja el sonido.",
        relacionados: ["Onda", "Luz", "Espejo", "Refracción"]
    },
    {
        id: 51,
        termino: "Refracción",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Cambio de dirección de una onda al pasar entre medios diferentes.",
        definicionCompleta: "La refracción se debe al cambio de velocidad de la onda en diferentes medios.",
        formula: "n₁sen(θ₁) = n₂sen(θ₂) (Ley de Snell)",
        ejemplo: "Una pajita en agua parece doblada por refracción.",
        relacionados: ["Luz", "Índice de refracción", "Lente", "Prisma"]
    },
    {
        id: 52,
        termino: "Lente",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Dispositivo óptico que converge o diverge rayos de luz.",
        definicionCompleta: "Las lentes utilizan refracción para formar imágenes o enfocar luz.",
        formula: "1/f = 1/do + 1/di (ecuación lentes)",
        ejemplo: "Las gafas, lupas y cámaras usan lentes.",
        relacionados: ["Refracción", "Luz", "Imagen", "Foco"]
    },
    {
        id: 53,
        termino: "Espectro",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Distribución de la luz por longitudes de onda o frecuencias.",
        definicionCompleta: "El espectro electromagnético incluye radio, microondas, luz visible, rayos X.",
        formula: "c = λf (velocidad luz = longitud × frecuencia)",
        ejemplo: "El arcoíris muestra el espectro visible de la luz.",
        relacionados: ["Luz", "Frecuencia", "Longitud de onda", "Color"]
    },
    {
        id: 54,
        termino: "Fotón",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Partícula de luz sin masa y con energía cuantizada.",
        definicionCompleta: "El fotón es el cuanto de energía electromagnética, mediador de la fuerza electromagnética.",
        formula: "E = hf (energía = constante Planck × frecuencia)",
        ejemplo: "Los paneles solares convierten fotones en electricidad.",
        relacionados: ["Luz", "Energía", "Cuántico", "Electromagnético"]
    },
    {
        id: 55,
        termino: "Plasma",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Estado de la materia con gases ionizados a alta temperatura.",
        definicionCompleta: "El plasma es el cuarto estado de la materia, compuesto por iones y electrones libres.",
        formula: "Gas + Energía → Plasma ionizado",
        ejemplo: "El Sol, los rayos y las auroras son plasma.",
        relacionados: ["Ion", "Temperatura", "Estado de la materia", "Estrella"]
    },
    {
        id: 56,
        termino: "Fusión nuclear",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Unión de núcleos ligeros para formar núcleos más pesados.",
        definicionCompleta: "La fusión nuclear libera energía cuando núcleos ligeros se combinan.",
        formula: "²H + ³H → ⁴He + n + energía",
        ejemplo: "El Sol genera energía por fusión de hidrógeno.",
        relacionados: ["Núcleo", "Energía", "Hidrógeno", "Helio"]
    },
    {
        id: 57,
        termino: "Fisión nuclear",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "División de núcleos pesados en núcleos más ligeros.",
        definicionCompleta: "La fisión nuclear libera energía cuando núcleos pesados se dividen.",
        formula: "²³⁵U + n → fragmentos + neutrones + energía",
        ejemplo: "Las centrales nucleares usan fisión de uranio.",
        relacionados: ["Núcleo", "Uranio", "Neutron", "Radiactividad"]
    },
    {
        id: 58,
        termino: "Semiconductor",
        categoria: "fisica",
        nivel: "avanzado",
        definicionCorta: "Material con conductividad eléctrica intermedia.",
        definicionCompleta: "Los semiconductores conducen electricidad mejor que aislantes pero peor que conductores.",
        formula: "Banda prohibida ~ 1-3 eV",
        ejemplo: "Silicio y germanio son semiconductores básicos.",
        relacionados: ["Corriente eléctrica", "Electrón", "Cristal", "Tecnología"]
    },
    {
        id: 59,
        termino: "Polímero",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Macromolécula formada por repetición de unidades pequeñas.",
        definicionCompleta: "Los polímeros son cadenas largas de monómeros unidos por enlaces covalentes.",
        formula: "nA → (-A-)n (polimerización)",
        ejemplo: "Plástico, DNA, proteínas son polímeros.",
        relacionados: ["Molécula", "Covalente", "Monómero", "Plástico"]
    },
    {
        id: 60,
        termino: "Combustión",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Reacción química rápida que libera energía con oxígeno.",
        definicionCompleta: "La combustión es una reacción exotérmica entre un combustible y oxígeno.",
        formula: "Combustible + O₂ → CO₂ + H₂O + energía",
        ejemplo: "Quemar madera, gas o gasolina son combustiones.",
        relacionados: ["Reacción química", "Oxígeno", "Energía", "Exotérmica"]
    },
    {
        id: 61,
        termino: "Aleación",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Mezcla de metales con propiedades mejoradas.",
        definicionCompleta: "Las aleaciones combinan metales para obtener características superiores.",
        formula: "Metal base + Metal añadido = Aleación",
        ejemplo: "Acero (hierro + carbono), bronce (cobre + estaño).",
        relacionados: ["Metal", "Mezcla", "Propiedades", "Material"]
    },
    {
        id: 62,
        termino: "Corrosión",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Deterioro de metales por reacciones químicas con el ambiente.",
        definicionCompleta: "La corrosión es la oxidación destructiva de metales expuestos al ambiente.",
        formula: "Metal + O₂ + H₂O → Óxido metálico",
        ejemplo: "El óxido del hierro (herrumbre) es corrosión.",
        relacionados: ["Oxidación", "Metal", "Oxígeno", "Herrumbre"]
    },
    {
        id: 63,
        termino: "Viscosidad",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Resistencia de un fluido a fluir o deformarse.",
        definicionCompleta: "La viscosidad mide la fricción interna entre las capas de un fluido.",
        formula: "η = τ/(dv/dy) (coeficiente viscosidad)",
        ejemplo: "La miel es más viscosa que el agua.",
        relacionados: ["Fluido", "Fricción", "Liquido", "Deformación"]
    },
    {
        id: 64,
        termino: "Tensión superficial",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Fuerza que actúa en la superficie de los líquidos.",
        definicionCompleta: "La tensión superficial permite que algunos objetos floten en agua.",
        formula: "γ = F/L (fuerza por unidad longitud)",
        ejemplo: "Los insectos pueden caminar sobre el agua.",
        relacionados: ["Liquido", "Superficie", "Fuerza", "Capilaridad"]
    },
    {
        id: 65,
        termino: "Capilaridad",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Subida o bajada de líquidos en tubos estrechos.",
        definicionCompleta: "La capilaridad se debe a la adhesión y cohesión molecular.",
        formula: "h ∝ 1/r (altura inversamente proporcional al radio)",
        ejemplo: "El agua sube en una pajita estrecha.",
        relacionados: ["Tensión superficial", "Adhesión", "Cohesión", "Tubo"]
    },
    {
        id: 66,
        termino: "Difusión",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Movimiento de partículas de zonas concentradas a diluidas.",
        definicionCompleta: "La difusión es el transporte de masa por gradientes de concentración.",
        formula: "J = -D(dC/dx) (Ley de Fick)",
        ejemplo: "El perfume se extiende por difusión en el aire.",
        relacionados: ["Concentración", "Gradiente", "Transporte", "Movimiento"]
    },
    {
        id: 67,
        termino: "Sublimación",
        categoria: "quimica",
        nivel: "intermedio",
        definicionCorta: "Cambio directo de sólido a gas sin pasar por líquido.",
        definicionCompleta: "La sublimación ocurre cuando un sólido pasa directamente a fase gaseosa.",
        formula: "Sólido → Gas (sin fase líquida)",
        ejemplo: "El hielo seco (CO₂ sólido) sublima a -78°C.",
        relacionados: ["Estado de la materia", "Temperatura", "Presión", "Cambio de fase"]
    },
    {
        id: 68,
        termino: "Condensación",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Cambio de gas a líquido por enfriamiento.",
        definicionCompleta: "La condensación ocurre cuando un gas pierde energía y se convierte en líquido.",
        formula: "Gas → Líquido + calor latente",
        ejemplo: "El vapor de agua se condensa en las ventanas frías.",
        relacionados: ["Evaporación", "Temperatura", "Calor latente", "Punto de rocío"]
    },
    {
        id: 69,
        termino: "Evaporación",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Cambio de líquido a gas en la superficie.",
        definicionCompleta: "La evaporación es la vaporización que ocurre solo en la superficie del líquido.",
        formula: "Líquido + calor → Gas",
        ejemplo: "El agua de los charcos se evapora al sol.",
        relacionados: ["Condensación", "Vaporización", "Calor", "Superficie"]
    },
    {
        id: 70,
        termino: "Punto de fusión",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Temperatura a la cual un sólido se convierte en líquido.",
        definicionCompleta: "El punto de fusión es característico de cada sustancia pura.",
        formula: "Sólido ⇌ Líquido (a Tfusión)",
        ejemplo: "El hielo se funde a 0°C, el hierro a 1538°C.",
        relacionados: ["Temperatura", "Fusión", "Sólido", "Punto de ebullición"]
    },
    {
        id: 71,
        termino: "Punto de ebullición",
        categoria: "quimica",
        nivel: "basico",
        definicionCorta: "Temperatura a la cual un líquido se convierte en gas.",
        definicionCompleta: "El punto de ebullición depende de la presión atmosférica.",
        formula: "Líquido ⇌ Gas (a Tebullición)",
        ejemplo: "El agua hierve a 100°C al nivel del mar.",
        relacionados: ["Temperatura", "Presión", "Líquido", "Punto de fusión"]
    },
    {
        id: 72,
        termino: "Elasticidad",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Capacidad de un material para recuperar su forma original.",
        definicionCompleta: "La elasticidad permite que un objeto deformado vuelva a su estado inicial.",
        formula: "F = kx (Ley de Hooke)",
        ejemplo: "Un resorte es elástico, se estira y regresa.",
        relacionados: ["Deformación", "Fuerza", "Ley de Hooke", "Material"]
    },
    {
        id: 73,
        termino: "Inercia",
        categoria: "fisica",
        nivel: "basico",
        definicionCorta: "Tendencia de un objeto a mantener su estado de movimiento.",
        definicionCompleta: "La inercia es la resistencia al cambio de velocidad según la Primera Ley de Newton.",
        formula: "Primera Ley de Newton: F = 0 → a = 0",
        ejemplo: "Un pasajero se mueve hacia adelante al frenar bruscamente.",
        relacionados: ["Masa", "Velocidad", "Primera Ley de Newton", "Movimiento"]
    },
    {
        id: 74,
        termino: "Centrifuga",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Fuerza aparente hacia afuera en movimiento circular.",
        definicionCompleta: "La fuerza centrífuga es una fuerza ficticia en sistemas de referencia rotatorios.",
        formula: "Fc = mω²r (fuerza centrífuga)",
        ejemplo: "Te empuja hacia afuera en una montaña rusa circular.",
        relacionados: ["Movimiento circular", "Fuerza", "Aceleración", "Rotación"]
    },
    {
        id: 75,
        termino: "Centripeta",
        categoria: "fisica",
        nivel: "intermedio",
        definicionCorta: "Fuerza dirigida hacia el centro en movimiento circular.",
        definicionCompleta: "La fuerza centrípeta mantiene un objeto en trayectoria circular.",
        formula: "Fc = mv²/r (fuerza centrípeta)",
        ejemplo: "La gravedad actúa como fuerza centrípeta en órbitas.",
        relacionados: ["Movimiento circular", "Gravedad", "Órbita", "Aceleración"]
    }
];